#任务基础包名
uw:
  task:
    enable-task-registry: true
    project: com.demo.task
    #任务管理服务器地址
    server-host: http://192.168.88.88:58080
    # 主机名
    host-id: Dev Machine
    # 私有模式。不运行全局target任务。
    privacy-mode: false
    # croner线程数
    croner-thread-num: 3
    task-log-min-thread-num: 10
    task-log-max-thread-num: 200
    task-rpc-min-thread-num: 1
    task-rpc-max-thread-num: 200

    # rabbitmq
    rabbitmq:
      host: 192.168.88.67
      port: 5672
      username: admin
      password: leleku51766
      publisher-confirms: true
      virtual-host: /
  
    # redis 缓存
    redis:
      database: 6
      host: 192.168.88.67
      port: 6379
      password: "Yrw@oYMSXO0fkXJzGKzC!85jmu27Ey"
      lettuce:
        pool:
          max-active: 20
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
        timeout: 30s

  #任务管理服务器认证相关配置
  auth:
    client:
      enable-spring-cloud: false
      auth-server: http://192.168.88.88:9110
      login-entry-point: /api/auth/login
      refresh-entry-point: /api/auth/token
      username: acris
      password: 123456
      user-type: 1
      exit-on-auth-failed: false
      http-pool:
        max-total: 1000
        default-max-per-route: 1000
        connect-timeout: 1000
        connection-request-timeout: 1000
        socket-timeout: 1000
        keep-alive-time-if-not-present: 0
  log:
    es-config:
      clusters: http://localhost:9200